### ISSUE TITLE
dealing with batch effects?

### ISSUE THREAD

**Issue by gudeqing** [ttgump/scDeepCluster_pytorch#1]
Hi, can this method be able to dealing with batch effects?

**Comment by ttgump** [comment]
Hi,
I have made a script "run_scDeepClusterBatch.py" to deal with batch effects. The script uses the conditional autoencoder to merge different batches. The batch IDs should be stored in matrix "B", which is a one-hot-encoding matrix. For example, if you have 3 batches, then encode the batches as [1 0 0], [0 1 0], [0 0 1]. Thanks.
