### ISSUE TITLE
About geneSelection function

### ISSUE THREAD

**Issue by weipeng008005** [ttgump/scDeepCluster_pytorch#2]
I want know where the “geneSelection” function in single_cell_tools.py come from?
Is it from other paper or author's original work?

**Comment by ttgump** [comment]
Hi,
It comes from the paper "Kobak, D., & Berens, P. (2019). The art of using t-SNE for single-cell transcriptomics. Nature communications, 10(1), 5416."
The code: [https://github.com/berenslab/rna-seq-tsne/blob/master/rnaseqTools.py](https://github.com/berenslab/rna-seq-tsne/blob/master/rnaseqTools.py)

**Comment by weipeng008005** [comment]
Thx！
