### ISSUE TITLE
Issue Opening .hdf5 file

### ISSUE THREAD

**Issue by compbiolover** [ttgump/scDeepCluster_pytorch#3]
Hi,
I have a scRNA-seq `.csv` file that I have converted to `.hdf5` format that is fairly large that is causing an error with `scDeepCluster.` I had to take a custom function from [here](https://stackoverflow.com/questions/16639503/unable-to-save-dataframe-to-hdf5-object-header-message-is-too-large) in order to convert it to `.hdf5` format and I believe it is causing the error I am seeing. You mention in the documentation to include an X component and I am not sure how to do that within my setup. Happy to share my conversion code and data. Thanks for such a cool tool! A screenshot of the error is attached: 
![Screenshot 2023-03-20 at 3 23 17 PM](https://user-images.githubusercontent.com/39838470/226444784-a27546dc-8648-4029-ba25-04008919603f.png)

Andrew

**Comment by ttgump** [comment]
Hi,
According to the error message, it seems you didn't create a "X" object in the h5 file. Here is my R sample code to save h5 file:

>h5createFile('data.h5')
>h5write(counts, "data.h5", "X")
>h5write(rownames(counts), "data.h5", "genes")
>h5write(colnames(counts), "data.h5", "cells")
>h5write(labels, "data.h5", "Y")

The "rhdf5" package is needed. Note that here row names are genes and column names are cells, since R and python have different indexing when writing h5 file. If you use the R code to generate h5 file and load it in python, in the X matrix, rows are cells and columns are genes. It might be some tricky.

You can also create your own h5 file by python, but remember to create the "X" matrix in it.

**Comment by handesome** [comment]
hi，i'm still confused,I only have the expression datafile .how to get the labels？Thanks

**Comment by ttgump** [comment]
> hi，i'm still confused,I only have the expression datafile .how to get the labels？Thanks

You don't need the labels. Labels are only used for evaluating the clustering performance (ARI, NMI, etc). Just store expression as "X" matrix in the h5 file.
Thanks.

**Comment by handesome** [comment]
> > hi，i'm still confused,I only have the expression datafile .how to get the labels？Thanks
> 
> You don't need the labels. Labels are only used for evaluating the clustering performance (ARI, NMI, etc). Just store expression as "X" matrix in the h5 file. Thanks.

oh！that's right.thank you for the reply.

**Comment by handesome** [comment]
excuse me，hi！when i run the code in my own data,the error said
`Make sure that the dataset (adata.X) contains unnormalized count data`,
so is there any suggstion to solve the problem? only the unnormalized count data could be used?
Thanks!!

**Comment by ttgump** [comment]
> excuse me，hi！when i run the code in my own data,the error said
> `Make sure that the dataset (adata.X) contains unnormalized count data`,
> so is there any suggstion to solve the problem? only the unnormalized count data could be used?
> Thanks!!

Yes, only discrete counts are accepted as input. scDeepCluster uses ZINB distribution to characterize scRNA-seq data. I think the error message is given by scanpy package. You can trim you data to discrete counts.

**Comment by handesome** [comment]
I'm sorry to bother you again. When I  trim my data later,the error is attached.
`TypeError: void() takes exactly 1 positional arguments (0 given)`
it drives me crazy now. I am grateful for your kind assistance.
Thank you again！！

**Comment by ttgump** [comment]
> I'm sorry to bother you again. When I trim my data later,the error is attached.
> `TypeError: void() takes exactly 1 positional arguments (0 given)`
> it drives me crazy now. I am grateful for your kind assistance.
> Thank you again！！

What line generates the error message? Could you also present a sample of your data?

**Comment by handesome** [comment]
![image](https://github.com/ttgump/scDeepCluster_pytorch/assets/56467838/ce2c7e09-7386-4925-b810-110dd2237db1)
![image](https://github.com/ttgump/scDeepCluster_pytorch/assets/56467838/474d779a-f966-4451-b71c-ebb83cf151b1)
![image](https://github.com/ttgump/scDeepCluster_pytorch/assets/56467838/e657a59c-a2bb-4120-8106-f325225c0285)
Thank you for the reply！！there are the pictures about error message and my data.may them could help you to understand.if i need to do something else,please tell me.Thanks!!!!!

**Comment by handesome** [comment]
and if I just store expression as "X" matrix in the h5 file. There are noting wrong, everything  goes well.

**Comment by ttgump** [comment]
> ![image](https://user-images.githubusercontent.com/56467838/257051258-ce2c7e09-7386-4925-b810-110dd2237db1.png)
> ![image](https://user-images.githubusercontent.com/56467838/257051574-474d779a-f966-4451-b71c-ebb83cf151b1.png)
> ![image](https://user-images.githubusercontent.com/56467838/257051388-e657a59c-a2bb-4120-8106-f325225c0285.png)
> Thank you for the reply！！there are the pictures about error message and my data.may them could help you to understand.if i need to do something else,please tell me.Thanks!!!!!

The error message comes from scanpy package. Could you tell me the version of your scanpy package?

**Comment by handesome** [comment]
![image](https://github.com/ttgump/scDeepCluster_pytorch/assets/56467838/a0d0dc9c-bb04-4cfb-8f3e-a9fc509cd33d)
The scanpy versin is 1.9.3.which version of scanpy could be OK?Thank you for the reply.

**Comment by handesome** [comment]
i see，it's all my fault. I will change the version to 1.7.2.Thanks

**Comment by handesome** [comment]
i have changed the scanpy version to 1.7.2,but it didn't work.so sad.

**Comment by ttgump** [comment]
> i have changed the scanpy version to 1.7.2,but it didn't work.so sad.

I can't see any problem of your screenshot. Could you share a sample data with me? Meanwhile, I noticed that your data is so small, there are only 90 cells. It may not a good idea to apply deep learning to a so small dataset.

**Comment by handesome** [comment]
Sure，my email count 17323376631@163.com.or could you tell me your e-mail?my data is small cause I just want to test my datafile is OK or not. I will change the dataset if everything goes right, Thanks.

**Comment by ttgump** [comment]
> > i have changed the scanpy version to 1.7.2,but it didn't work.so sad.
> 
> I can't see any problem of your screenshot. Could you share a sample data with me? Meanwhile, I noticed that your data is so small, there are only 90 cells. It may not a good idea to apply deep learning to a so small dataset.

My email address is on my GitHub page

**Comment by ttgump** [comment]
> Sure，my email count [17323376631@163.com.or](mailto:17323376631@163.com.or) could you tell me your e-mail?my data is small cause I just want to test my datafile is OK or not. I will change the dataset if everything goes right, Thanks.

I find your problem. You store "y" as an array of vectors. Here is your "y" vector:
`
array([(1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (2.,), (2.,), (2.,),
       (2.,), (2.,), (2.,), (3.,), (3.,), (3.,), (3.,), (3.,), (3.,),
       (3.,), (3.,), (3.,), (3.,), (3.,), (3.,), (4.,), (4.,), (4.,),
       (4.,), (4.,), (4.,), (4.,), (4.,), (4.,), (4.,), (4.,), (4.,),
       (4.,), (4.,), (4.,), (4.,), (4.,), (4.,), (4.,), (4.,), (5.,),
       (5.,), (5.,), (5.,), (5.,), (5.,), (5.,), (5.,), (5.,), (5.,),
       (5.,), (5.,), (5.,), (5.,), (5.,), (5.,), (6.,), (6.,), (6.,),
       (6.,), (6.,), (6.,), (6.,), (6.,), (6.,), (6.,), (6.,), (6.,),
       (6.,), (6.,), (6.,), (6.,), (6.,), (6.,), (6.,), (6.,), (6.,),
       (6.,), (6.,), (6.,), (6.,), (6.,), (6.,), (6.,), (6.,), (6.,)],
      dtype=[('V1', '<f8')])
`

However, a preferred "y" should be a 1-D vector such as [1, 1, 1, ...]
